### ISSUE TITLE
Incompatible with obspy>=1.5.0

### ISSUE THREAD

**Issue by zhong-yy** [eqcorrscan/EQcorrscan#613]
**Describe the bug**
When obspy 1.4.2 is used, the following error occur:
```
File ~/miniconda3/envs/eqcorrscan0.5/lib/python3.10/site-packages/eqcorrscan/core/match_filter/tribe.py:967, in <listcomp>(.0)
    965     continue
    966 for i, template_group in enumerate(template_groups):
--> [967] templates = [_quick_copy_stream(t.st) for t in template_group]
    968     template_names = [t.name for t in template_group]
    969     Logger.info(
    970         f"Prepping {len(templates)} templates for correlation")
...
--> [928]        ns=value_2.__dict__['_UTCDateTime__ns'])
    929     else:
    930         new_stats.__dict__[key_2] = value_2

AttributeError: 'UTCDateTime' object has no attribute '__dict__'
``` 
This error seems to be caused by https://github.com/eqcorrscan/EQcorrscan/blob/ea947c4bc935ab8bce5de29cbca21ad37537f544/eqcorrscan/utils/pre_processing.py#L927-L928

**To Reproduce**
Steps to reproduce the behaviour (including error messages if applicable - if this gets really long, maybe make a gist?)
(1) Run any example with obspy 1.4.2
(2) Try runing the following snippet with obspy 1.4.2 and obspy 1.4.1 respectively
```python
t = UTCDateTime.now()
UTCDateTime(ns=t.__dict__["_UTCDateTime__ns"])
```

**Expected behavior**

**Desktop (please complete the following information):**
 - Operating System: ubuntu
 - Python version: python>=3.10
 - EQcorrscan version: 0.5.2

**Comment by calum-chamberlain** [comment]
Thanks for spotting that and apologies! I will try and get a fix going - we should probably push out a new release here that supports obspy 1.5 and python 3.14.

**Comment by calum-chamberlain** [comment]
So for me this works in both obspy 1.4.1 and 1.4.2, and I don't see any changes at obspy that would have caused this between 1.4.1 and 1.4.2, however this doesn't work with obspy 1.5.0 which I think stems from the change to using slots in [this PR](https://github.com/obspy/obspy/pull/3695).

I'm going to amend the title of this issue to reflect the correct obspy version.

**Comment by calum-chamberlain** [comment]
~~@d-chambers I think this might have been your speed-up addition to EQcorrscan and you know the change at obspy best. Any suggestions of how best to access the `ns` on `UTCDateTime` now? I think when we make this change we might be restricting ourselves to obspy>=1.5.~~

Apologies, it was @flixha who added that change in [this commit](https://github.com/eqcorrscan/EQcorrscan/commit/0fc5ec7798a9c3e72bcf38a7636ac375046b5525).  Accessing `t.ns` directly is an extra 10ns on my machine vs going directly to `__dict__["_UTCDateTime__ns"]` (32 vs 22 ns). I don't think this is worth chasing, so I'm going to change to accessing the public `t.ns` attribute.

**Comment by zhong-yy** [comment]
Thanks for the quick fix!

**Comment by zhong-yy** [comment]
Btw, I couldn't install from source using `pip install .`, with the following error:
```
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × installing build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Collecting setuptools
        Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
      Collecting numpy
        Downloading numpy-2.4.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
      ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.26.0 Requires-Python >=3.9,<3.13; 1.26.1 Requires-Python >=3.9,<3.13
      ERROR: Could not find a version that satisfies the requirement pkg-resources (from versions: none)
      ERROR: No matching distribution found for pkg-resources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
``

**Comment by calum-chamberlain** [comment]
Ah darn, I removed the need for pkg-resources, but didn't actually remove it as a build dependency. I'm just running a test locally then I will fix that @zhong-yy.

**Comment by calum-chamberlain** [comment]
Should now be patched in master
